apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
  POSTGRES_DB: devops_db
  DATABASE_URL: postgresql://admin:admin123@postgres:5432/devops_db
